"""
Generate the comprehensive pesticide knowledge base for GrapeGuard AI.
Run this script once to create/update data/pesticides.xlsx.
"""

import pandas as pd
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parents[0] / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

rows = [
    # ── Downy Mildew ──────────────────────────────────────────────────────
    {
        "disease_name": "Downy Mildew",
        "symptoms": "yellow oil spots on upper leaf surface, white fungal growth on underside of leaves, brown necrotic patches on severely affected leaves",
        "pesticide_name": "Metalaxyl + Mancozeb",
        "dosage": "2 g/L",
        "schedule": "Spray every 7-10 days during wet weather",
        "notes": "Systemic + contact action, avoid spraying before rain",
        "source": "ICAR",
    },
    {
        "disease_name": "Downy Mildew",
        "symptoms": "yellow oil spots on upper leaf surface, white fungal growth on underside",
        "pesticide_name": "Copper Hydroxide 77% WP",
        "dosage": "2.5 g/L",
        "schedule": "Preventive spray every 10-14 days",
        "notes": "Contact fungicide, apply before disease appears",
        "source": "ICAR",
    },
    {
        "disease_name": "Downy Mildew",
        "symptoms": "yellow oil spots, downy white growth under leaves",
        "pesticide_name": "Bordeaux Mixture",
        "dosage": "1% solution (1 kg CuSO4 + 1 kg lime in 100L water)",
        "schedule": "Spray at 15-day intervals",
        "notes": "Traditional copper-based organic fungicide, safe for organic farming",
        "source": "State Agriculture Department",
    },
    {
        "disease_name": "Downy Mildew",
        "symptoms": "yellow oil spots on upper leaf surface, white fungal growth on underside",
        "pesticide_name": "Dimethomorph 50% WP",
        "dosage": "1 g/L",
        "schedule": "Apply at first sign of disease, repeat every 10-14 days",
        "notes": "Systemic fungicide, effective against resistant strains",
        "source": "ICAR",
    },
    {
        "disease_name": "Downy Mildew",
        "symptoms": "oily yellow spots, white downy growth on underside of leaves",
        "pesticide_name": "Neem Oil (Azadirachtin)",
        "dosage": "3-5 mL/L",
        "schedule": "Spray every 7 days as preventive",
        "notes": "Organic botanical fungicide, also controls insects",
        "source": "Organic Farming Manual",
    },
    {
        "disease_name": "Downy Mildew",
        "symptoms": "yellow oil spots, white sporulation on leaf undersides",
        "pesticide_name": "Bio-Trichoderma viride",
        "dosage": "5 g/L",
        "schedule": "Apply at 10-14 day intervals",
        "notes": "Biological organic control agent, safe for environment",
        "source": "NBAIR",
    },
    # ── Powdery Mildew ────────────────────────────────────────────────────
    {
        "disease_name": "Powdery Mildew",
        "symptoms": "powdery white coating on leaves and berries, leaf curling, premature fruit drop",
        "pesticide_name": "Sulfur 80% WP",
        "dosage": "2 g/L",
        "schedule": "Spray every 10-14 days",
        "notes": "Do not spray in hot weather above 35°C, may cause leaf burn",
        "source": "State Agriculture Department",
    },
    {
        "disease_name": "Powdery Mildew",
        "symptoms": "white powdery patches on leaves and young shoots, berry splitting",
        "pesticide_name": "Triadimefon 25% WP",
        "dosage": "0.5 g/L",
        "schedule": "Spray at initial symptoms, repeat after 14 days",
        "notes": "Systemic triazole fungicide, alternate with contact fungicides",
        "source": "ICAR",
    },
    {
        "disease_name": "Powdery Mildew",
        "symptoms": "powdery white coating on leaves, shoots, and fruit",
        "pesticide_name": "Hexaconazole 5% EC",
        "dosage": "1 mL/L",
        "schedule": "Spray at 15-day intervals",
        "notes": "Broad-spectrum systemic fungicide",
        "source": "ICAR",
    },
    {
        "disease_name": "Powdery Mildew",
        "symptoms": "powdery white coating on foliage, stunted growth",
        "pesticide_name": "Baking Soda (Sodium Bicarbonate)",
        "dosage": "5 g/L with 2 mL liquid soap",
        "schedule": "Spray every 7 days as preventive",
        "notes": "Safe organic home remedy, prevents spore germination",
        "source": "Organic Farming Manual",
    },
    {
        "disease_name": "Powdery Mildew",
        "symptoms": "white powdery mold on leaf surfaces, berry deformation",
        "pesticide_name": "Neem Oil (Azadirachtin)",
        "dosage": "5 mL/L",
        "schedule": "Spray weekly during susceptible period",
        "notes": "Organic botanical fungicide, also acts as insect repellent",
        "source": "Organic Farming Manual",
    },
    {
        "disease_name": "Powdery Mildew",
        "symptoms": "white powdery spots on leaves and berries",
        "pesticide_name": "Bio-Ampelomyces quisqualis",
        "dosage": "5 g/L",
        "schedule": "Apply at 10-14 day intervals",
        "notes": "Biological organic hyperparasite of powdery mildew fungus",
        "source": "NBAIR",
    },
    # ── Anthracnose ───────────────────────────────────────────────────────
    {
        "disease_name": "Anthracnose",
        "symptoms": "dark sunken lesions on berries and shoots, bird's eye spot on fruit, black spots on leaves",
        "pesticide_name": "Carbendazim 50% WP",
        "dosage": "1 g/L",
        "schedule": "2-3 sprays at 10-day intervals",
        "notes": "Systemic fungicide, use clean pruning tools to prevent spread",
        "source": "ICAR",
    },
    {
        "disease_name": "Anthracnose",
        "symptoms": "dark sunken lesions, necrotic spots on leaves and berries",
        "pesticide_name": "Mancozeb 75% WP",
        "dosage": "2.5 g/L",
        "schedule": "Spray every 10-14 days during rainy season",
        "notes": "Broad-spectrum contact fungicide, good protectant",
        "source": "ICAR",
    },
    {
        "disease_name": "Anthracnose",
        "symptoms": "sunken dark lesions on berries and shoots, shot-hole in leaves",
        "pesticide_name": "Thiophanate-methyl 70% WP",
        "dosage": "1 g/L",
        "schedule": "Spray at 10-14 day intervals from bud break",
        "notes": "Systemic fungicide, effective against established infections",
        "source": "State Agriculture Department",
    },
    {
        "disease_name": "Anthracnose",
        "symptoms": "dark sunken lesions on fruit, bird's eye spots",
        "pesticide_name": "Copper Oxychloride 50% WP",
        "dosage": "3 g/L",
        "schedule": "Spray at 10-14 day intervals",
        "notes": "Contact copper fungicide, effective preventive measure",
        "source": "State Agriculture Department",
    },
    {
        "disease_name": "Anthracnose",
        "symptoms": "dark sunken spots, lesions on berries and shoots",
        "pesticide_name": "Neem Oil (Azadirachtin)",
        "dosage": "5 mL/L",
        "schedule": "Spray every 7-10 days as preventive",
        "notes": "Organic botanical fungicide, eco-friendly approach",
        "source": "Organic Farming Manual",
    },
    {
        "disease_name": "Anthracnose",
        "symptoms": "dark lesions, bird's eye spot, necrotic areas",
        "pesticide_name": "Bio-Pseudomonas fluorescens",
        "dosage": "5 g/L",
        "schedule": "Apply as soil drench and foliar spray every 15 days",
        "notes": "Biological organic control agent, promotes plant health",
        "source": "NBAIR",
    },
    # ── Black Rot ─────────────────────────────────────────────────────────
    {
        "disease_name": "Black Rot",
        "symptoms": "reddish-brown circular lesions on leaves, dark shriveled mummified berries, cankers on shoots",
        "pesticide_name": "Myclobutanil 10% WP",
        "dosage": "0.5 g/L",
        "schedule": "Start at bud break, repeat every 10-14 days",
        "notes": "Systemic triazole fungicide, protectant and curative",
        "source": "ICAR",
    },
    {
        "disease_name": "Black Rot",
        "symptoms": "circular brown lesions on leaves, black mummified fruit, shoot cankers",
        "pesticide_name": "Mancozeb 75% WP",
        "dosage": "2.5 g/L",
        "schedule": "Spray every 10-14 days from bud break through fruit set",
        "notes": "Contact fungicide, good protectant when applied before infection",
        "source": "State Agriculture Department",
    },
    {
        "disease_name": "Black Rot",
        "symptoms": "tan circular leaf spots, black shriveled fruit",
        "pesticide_name": "Neem Oil (Azadirachtin)",
        "dosage": "5 mL/L",
        "schedule": "Spray every 7-10 days",
        "notes": "Organic botanical preventive, remove mummies and infected debris",
        "source": "Organic Farming Manual",
    },
    # ── Leaf Blight ───────────────────────────────────────────────────────
    {
        "disease_name": "Leaf Blight",
        "symptoms": "irregular brown to black necrotic patches on leaves, premature defoliation, reduced vigor",
        "pesticide_name": "Chlorothalonil 75% WP",
        "dosage": "2 g/L",
        "schedule": "Spray every 10-14 days during disease-favorable weather",
        "notes": "Broad-spectrum contact fungicide, do not mix with alkaline sprays",
        "source": "ICAR",
    },
    {
        "disease_name": "Leaf Blight",
        "symptoms": "brown necrotic patches on leaves, defoliation",
        "pesticide_name": "Copper Hydroxide 77% WP",
        "dosage": "2 g/L",
        "schedule": "Spray at 10-14 day intervals",
        "notes": "Contact copper fungicide, preventive application",
        "source": "State Agriculture Department",
    },
    {
        "disease_name": "Leaf Blight",
        "symptoms": "irregular necrotic spots on leaves, premature leaf fall",
        "pesticide_name": "Bio-Trichoderma harzianum",
        "dosage": "5 g/L",
        "schedule": "Apply every 15 days as foliar spray",
        "notes": "Biological organic agent, strengthens plant defense",
        "source": "NBAIR",
    },
    # ── Rust ──────────────────────────────────────────────────────────────
    {
        "disease_name": "Rust",
        "symptoms": "small yellow-orange pustules on underside of leaves, premature leaf drop, weakened vines",
        "pesticide_name": "Triadimefon 25% WP",
        "dosage": "0.5 g/L",
        "schedule": "Spray at first symptom appearance, repeat after 14 days",
        "notes": "Systemic fungicide, effective against rust fungi",
        "source": "ICAR",
    },
    {
        "disease_name": "Rust",
        "symptoms": "yellow-orange pustules on leaves, defoliation",
        "pesticide_name": "Sulfur 80% WP",
        "dosage": "3 g/L",
        "schedule": "Spray every 10-14 days",
        "notes": "Avoid in hot weather, effective preventive against rust",
        "source": "State Agriculture Department",
    },
    {
        "disease_name": "Rust",
        "symptoms": "orange powdery pustules on leaf surfaces",
        "pesticide_name": "Neem Oil (Azadirachtin)",
        "dosage": "5 mL/L",
        "schedule": "Spray every 7 days during humid season",
        "notes": "Organic botanical preventive, remove infected leaves",
        "source": "Organic Farming Manual",
    },
    # ── Botrytis (Gray Mold) ─────────────────────────────────────────────
    {
        "disease_name": "Botrytis",
        "symptoms": "gray fuzzy mold on berries, blossom blight, bunch rot, wilt of flower clusters",
        "pesticide_name": "Iprodione 50% WP",
        "dosage": "1 g/L",
        "schedule": "Spray at bloom and pre-harvest if humid",
        "notes": "Dicarboximide fungicide, limit applications to avoid resistance",
        "source": "ICAR",
    },
    {
        "disease_name": "Botrytis",
        "symptoms": "gray mold on fruit clusters, blossom blight",
        "pesticide_name": "Carbendazim 50% WP",
        "dosage": "1 g/L",
        "schedule": "Spray at flowering and veraison",
        "notes": "Systemic fungicide, improve air circulation in canopy",
        "source": "State Agriculture Department",
    },
    {
        "disease_name": "Botrytis",
        "symptoms": "gray fuzzy mold, bunch rot",
        "pesticide_name": "Bio-Bacillus subtilis",
        "dosage": "5 g/L",
        "schedule": "Apply at bloom, repeat every 10-14 days",
        "notes": "Biological organic control, safe for beneficial insects",
        "source": "NBAIR",
    },
    # ── Healthy (no disease detected) ────────────────────────────────────
    {
        "disease_name": "Healthy",
        "symptoms": "no visible disease symptoms, normal green foliage, healthy fruit development",
        "pesticide_name": "No treatment required",
        "dosage": "N/A",
        "schedule": "Continue regular monitoring every 7-14 days",
        "notes": "Maintain vineyard hygiene, proper pruning, and balanced nutrition",
        "source": "General Best Practice",
    },
    {
        "disease_name": "Healthy",
        "symptoms": "healthy leaves and berries, no disease symptoms",
        "pesticide_name": "Neem Oil (Azadirachtin) - Preventive",
        "dosage": "2-3 mL/L",
        "schedule": "Optional preventive spray every 14-21 days",
        "notes": "Organic botanical preventive to maintain plant health",
        "source": "Organic Farming Manual",
    },
]

df = pd.DataFrame(rows)
df = df.fillna("")
output_path = DATA_DIR / "pesticides.xlsx"
df.to_excel(output_path, index=False)
print(f"Created {output_path} with {len(df)} entries")
print(f"Disease coverage: {sorted(df['disease_name'].unique())}")
